name: gFeatures
main: tk.genesishub.gFeatures.Listeners.Listeners
version: 1.0
load: STARTUP
commands:
   gFeatures:
     description: gFeatures core command.
     aliases: [gf, gFeature]
     permission: gFeatures.command.gFeatures
     usage: Syntax error! Do /gFeatures help for help.
softdepend: [Skript, CrackShot]