name: gFeatures
main: tk.genesishub.gFeatures.Listeners.Listeners
version: 1.0
load: STARTUP
commands:
   gFeatures:
     description: gFeatures core command.
     aliases: [gf, gFeature]
     permission: gFeatures.command.gFeatures
     usage: Syntax error! Do /gFeatures help for help.
   GenesisBackup:
     description: gBackup core command.
     aliases: [gBackup, GenesisBackup, gb]
     permission: gFeatures.command.gFeatures
     usage: Syntax error! Do /gFeatures help for help.
   spectate:
      description: Puts you in spectator mode.
      usage:
      permission: gWarsSuite.stats
      permission-message: You don't have <permission>
   listteams:
      description: Lists the teams.
      usage:
      permission: gWarsSuite.stats
      permission-message: You don't have <permission>
   st:
      description: Switches your team.
      usage:
      permission: gWarsSuite.stats
      permission-message: You don't have <permission>
   switchteams:
      description: Switches your team.
      usage:
      permission: gWarsSuite.stats
      permission-message: You don't have <permission>
   capture:
      description: Captures a point.
      usage: /capture 
      permission: gWarsSuite.capture
      permission-message: You don't have <permission>
   stats:
      description: Shows your stats.
      usage:
      permission: gWarsSuite.stats
      permission-message: You don't have <permission>
   c:
      description: Alias for /capture.
      usage: /c
      permission: gWarsSuite.capture
      permission-message: You don't have <permission>
   kit-tier0-sniper:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier0-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier0-auto-rifle:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier0-special:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier1-auto-rifle:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier1-sniper:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier1-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier1-special:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier2-special:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier2-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier2-sniper:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier2-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier2-auto-rifle:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier3-special:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier3-sniper:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier3-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier3-auto-rifle:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier4-special:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier4-sniper:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier4-shotgun:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   kit-tier4-auto-rifle:
      description: Technical Command.
      usage:
      permission: gWarsSuite.getgun
      permission-message: You don't have <permission>
   airfield:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   underground:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   turrets:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   mainfloor:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   town:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   island:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   tutorial:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   spawn:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   nuke:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   done:
      description: Technical Command.
      usage:
      permission: gWarsSuite.arenatp
      permission-message: You don't have <permission>
   admin-arena:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-gunin:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-airplaneline:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-bt:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-ot:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-clear-arena:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-clear-gunin:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-clear-airplaneline:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-takekills:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-givekills:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-givedeaths:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
   admin-takedeaths:
      description: Technical Command.
      usage:
      permission: gWarsSuite.admin
      permission-message: You don't have <permission>
softdepend: [Skript, CrackShot]