HecklerAndKochMP5:
    Item_Information:
        Item_Name: "&b&lHeckler & Koch MP-5&f&l"
        Item_Type: 279
        Item_Lore: "&eHeckler & Koch MP-5|&eTier 4 Auto-Rifle|&eTop tier auto-rifle."
        Melee_Mode: false
        Skip_Name_Check: false
        Sounds_Acquired: ENTITY_BAT_TAKEOFF-1-1-0
        Remove_Unused_Tag: false
        Hidden_From_List: false
    Shooting:
        Disable: false
        Dual_Wield: false
        Right_Click_To_Shoot: true
        Cancel_Left_Click_Block_Damage: true
        Cancel_Right_Click_Interactions: true
        Delay_Between_Shots: 0.5
        Recoil_Amount: 0
        Projectile_Amount: 1
        Projectile_Type: snowball
        Remove_Bullet_Drop: true
        Removal_Or_Drag_Delay: 15-false
        Projectile_Speed: 30
        Projectile_Damage: 7
        Projectile_Flames: false
        Projectile_Incendiary:
            Enable: false
        Bullet_Spread: 0.5
        Reset_Fall_Distance: true
        Sounds_Shoot: ENTITY_IRONGOLEM_ATTACK-1-2-0,ENTITY_SKELETON_HURT-1-2-0,ENTITY_ZOMBIE_ATTACK_DOOR_WOOD-1-2-0
    Fully_Automatic:
        Enable: true
        Fire_Rate: 10
    Sneak:
        Enable: false
    Ammo:
        Enable: true
        Ammo_Item_ID: 362
        Take_Ammo_Per_Shot: false
    Reload:
        Enable: true
        Reload_With_Mouse: false
        Starting_Amount: 150
        Reload_Amount: 150
        Reload_Bullets_Individually: false
        Take_Ammo_On_Reload: true
        Take_Ammo_As_Magazine: true
        Reload_Duration: 9
        Destroy_When_Empty: false
        Sounds_Out_Of_Ammo: 
        Sounds_Reloading:  ITEM_FIRECHARGE_USE-1-1-4,BLOCK_WOODEN_DOOR_OPEN-1-2-6,ITEM_FIRECHARGE_USE-1-1-36,ENTITY_PLAYER_HURT-1-0-37,BLOCK_WOODEN_DOOR_CLOSE-1-2-38
    Firearm_Action:
        Type: slide
        Open_Duration: 12
        Close_Duration: 12
        Close_Shoot_Delay: 3
        Sound_Open: BLOCK_NOTE_HAT-1-0-0,BLOCK_PISTON_CONTRACT-1-2-2
        Sound_Close: ITEM_FIRECHARGE_USE-1-1-4,BLOCK_WOODEN_DOOR_OPEN-1-2-6,ITEM_FIRECHARGE_USE-1-1-36,ENTITY_PLAYER_HURT-1-0-37,BLOCK_WOODEN_DOOR_CLOSE-1-2-38
    Scope:
        Enable: true
        Night_Vision: true
        Zoom_Amount: 5
        Zoom_Bullet_Spread: 0
        Zoom_Before_Shooting: false
        Sounds_Toggle_Zoom: BLOCK_NOTE_HAT-1-2-0
    Headshot:
        Enable: false
        Bonus_Damage: 15
        Message_Shooter: You got a headshot!
        Message_Victim: You've been headshoted!
        Sounds_Shooter: ENTITY_EXPERIENCE_ORB_PICKUP-1-2-0
        Sounds_Victim: ENTITY_EXPERIENCE_ORB_PICKUP-1-2-0
    Backstab:
        Enable: false
    Critical_Hits:
        Enable: false
    Spawn_Entity_On_Hit:
        Enable: false
    Damage_Based_On_Flight_Time:
        Enable: false
    Custom_Death_Message:
        Normal: "&b[&6Kill&b]&3 <shooter> killed <victim> using a &6Beretta-ARX100&3!"
