Shotgun:
    Item_Information:
        Item_Name: "&b&lShotgun&f&l"
        Item_Type: 269
        Item_Lore: "&eShotgun|&eClassic starter Shotgun|&eShoots multiple bullets at once but slow"
        Melee_Mode: false
        Skip_Name_Check: false
        Sounds_Acquired: ENTITY_BAT_TAKEOFF-1-1-0
        Remove_Unused_Tag: false
        Hidden_From_List: false
    Shooting:
        Disable: false
        Dual_Wield: false
        Right_Click_To_Shoot: true
        Cancel_Left_Click_Block_Damage: true
        Cancel_Right_Click_Interactions: true
        Delay_Between_Shots: 17
        Recoil_Amount: 5
        Projectile_Amount: 10
        Projectile_Type: snowball
        Remove_Bullet_Drop: true
        Removal_Or_Drag_Delay: 15-false
        Projectile_Speed: 30
        Projectile_Damage: 5
        Projectile_Flames: false
        Projectile_Incendiary:
            Enable: false
        Bullet_Spread: 1.3
        Reset_Fall_Distance: true
        Sounds_Shoot:  ENTITY_ZOMBIE_ATTACK_DOOR_WOOD-1-1-0,ENTITY_GENERIC_EXPLODE-1-2-0,ENTITY_GHAST_SHOOT-1-1-0
    Sneak:
        Enable: false
    Ammo:
        Enable: true
        Ammo_Item_ID: 362
        Take_Ammo_Per_Shot: false
    Reload:
        Enable: true
        Reload_With_Mouse: false
        Starting_Amount: 5
        Reload_Amount: 5
        Reload_Bullets_Individually: false
        Take_Ammo_On_Reload: true
        Take_Ammo_As_Magazine: false
        Reload_Duration: 15
        Destroy_When_Empty: false
        Sounds_Out_Of_Ammo: 
        Sounds_Reloading:  BLOCK_NOTE_HAT-1-1-0,BLOCK_NOTE_SNARE-1-6-1
    Firearm_Action:
        Type: break
        Open_Duration: 10
        Close_Duration: 15
        Close_Shoot_Delay: 3
        Sound_Open: BLOCK_WOODEN_DOOR_OPEN-1-2-0
        Sound_Close: BLOCK_WOODEN_DOOR_CLOSE-1-2-0
    Scope:
        Enable: false
        Night_Vision: true
        Zoom_Amount: 5
        Zoom_Bullet_Spread: 0
        Zoom_Before_Shooting: false
        Sounds_Toggle_Zoom: BLOCK_NOTE_HAT-1-2-0
    Headshot:
        Enable: false
        Bonus_Damage: 200
        Message_Shooter: You got a headshot!
        Message_Victim: You've been headshoted!
        Sounds_Shooter: ENTITY_EXPERIENCE_ORB_PICKUP-1-2-0
        Sounds_Victim: ENTITY_EXPERIENCE_ORB_PICKUP-1-2-0
    Backstab:
        Enable: false
    Critical_Hits:
        Enable: false
    Spawn_Entity_On_Hit:
        Enable: false
    Damage_Based_On_Flight_Time:
        Enable: false
    Custom_Death_Message:
        Normal: "&b[&6Kill&b]&3 <shooter> killed <victim> using a &6Shotgun&3!"