# Welcome to the gFeatures Main Config!
# Configure stuff here! (NO DUH)

#Specific plugins
gWarsSuite: false
gDestroyCritical: false
gHub: false
gFactions: false

#Presets
gWars: false
gDestroy: false
gHub: false
gFactions: false