name: gFeatures
main: net.estinet.gFeatures.Listeners
version: 3.3.10
load: STARTUP
commands:
   gFeatures:
     description: gFeatures core command.
     aliases: [gf, gFeature]
     permission: gFeatures.command.gFeatures
     usage: Syntax error! Do /gFeatures help for help.
   plugin:
     description: Shows the plugins on the server.
softdepend: [Skript, CrackShot, Factions]
